Use latest PNPM version if not specified (#81)
Co-authored-by: HiDeoo <494699+HiDeoo@users.noreply.github.com>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -38,6 +38,12 @@ runs:
         elif [ $(find "." -maxdepth 1 -name "pnpm-lock.yaml") ]; then
             echo "PACKAGE_MANAGER=pnpm" >> $GITHUB_ENV
             echo "LOCKFILE=pnpm-lock.yaml" >> $GITHUB_ENV
+            # If packageManager field is not present, use latest version.
+            if ! jq -e '.packageManager' package.json > /dev/null 2>&1; then
+                VERSION="latest"
+                # Annotate this action run to let users know we’re using the default.
+                echo "::warning title=Could not detect PNPM version::No \`packageManager\` field found in \`package.json\`. Using latest PNPM version instead. We recommend specifying \`pnpm@VERSION\` explicitly using the \`packageManager\` field in your \`package.json\`."
+            fi
         elif [ $(find "." -maxdepth 1 -name "yarn.lock") ]; then
             echo "PACKAGE_MANAGER=yarn" >> $GITHUB_ENV
             echo "LOCKFILE=yarn.lock" >> $GITHUB_ENV
